### ISSUE TITLE
Failed prop type: Invalid prop `ownProps` of type `object` supplied to `DataTableContainer`

### ISSUE THREAD

**Issue by RaitzeR** [sean-ww/react-redux-datatable#15]
Hi!
I get the below error and can't figure out why. The datatable loads correctly and actually 99% of the features work as expected. But for some reason the pagination text won't update. When inspecting the state, it does correctly change the currentPage value in the state, but in the view it's not updated. If I manually change the page number in the state, the frontend view will update and it shows the correct values in "Showing 11 to 20 of 22671 Results". 

So just to be clear: When clicking to another page, the text "Showing 1 to 10 of 22671 Results" won't change. The state value currentPage does change. Also if I manually change the currentPage value in state, the frontend part does change.

Warning: Failed prop type: Invalid prop `ownProps` of type `object` supplied to `DataTableContainer`, expected `function`.
    in DataTableContainer (created by Connect(DataTableContainer))
    in Connect(DataTableContainer) (at DataTable.js:47)
    in ExampleDataTable (at Catalog.js:14)
    in div (at Catalog.js:13)
    in Unknown (created by Route)
    in Route (at src/index.js:26)
    in div (at App.js:7)
    in Unknown (at src/index.js:24)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:23)
    in Provider (at src/index.js:22)

**Comment by RaitzeR** [comment]
After some further research, I think the pagination is it's own problem. Weirdly enough if I set pagination on the BootstrapTable component to a fixed value, like 4 it works. Also I modified the DataTableContainer a bit to allow page number to be saved in local storage. After this the pagination is correct when refreshing the site (getting the page from local storage), but after changing page, it always resets to 1, no matter what the original page or destination page was.
I checked the pagination options that goes to the paginationFactory and it has the correct page number. It's super weird...

**Comment by RaitzeR** [comment]
Ok got it fixed. I guess the paginationoptions gets messed up when the total size is 0 and we still treat it like there's pages. This fixed it.
I still have problems with the ownProps needing to be a function. I just removed the requirement so I don't get errors from it. Not sure if it's gonna have some weird effects though.

var paginationOptions = {};
        if (dataTotalSize !== 0) {
            paginationOptions = {
                page:  currentPage,
                paginationTotalRenderer: this.renderShowsTotal,
                showTotal: true,
                sizePerPage,
                sizePerPageList: [10, 25, 50, 100],
                onSizePerPageChange,
                totalSize: dataTotalSize,
            };
        }

**Comment by sean-ww** [comment]
Hi,
It's a shame something so simple causes such trouble. I'm in the process of removing the react-bootstrap-table2-paginator package and replacing it with a simplified version. That should then resolve your issue.

**Comment by RaitzeR** [comment]
Okay. I also developed infinity scroll which the user can enable by simply adding two parameters in the table configuration. If you’re interested I can branch it and put a pull request.

**Comment by sean-ww** [comment]
Sure, go ahead 👍
Please fork from develop

**Comment by sedhalsoni** [comment]
Hello,
I need to pass object id in actionFormatter function in edit and delete time but i am not able to pass object id in function.
please check my code and tell me where am i wrong.

    const apiLocation = 'http://localhost:3002/';
    const actionFormatter = () => (
        <div>
            <Link class="table-icons" to="editrecord">
                <span
                    class="edit link"
                />
            </Link>
            <Link class="table-icons" to="deleterecord">
                <span
                    class="delete link"
                />
            </Link>
        </div>
    );

    const tableSettings = {
        tableID: 'DataTable',
        wrapperType: 'section',
        displayTitle: 'DataTable',
        keyField: '_id',
        defaultSort: ['_id', 'desc'],
        minWidth: 880,
        useLocalStorage: true,
        tableColumns: [
            {
                title: 'First Name',
                key: 'firstName',
            },
            {
                title: 'Last Name',
                key: 'lastName',
            },
            {
                title: 'Email',
                key: 'email',
            },
            {
                title: 'Actions',
                key: '_id',
                searchable: false,
                sortable: false,
                export: false,
                dataFormat: actionFormatter,
            },
        ],
    };

Thanks ,
sedhal
