### ISSUE TITLE
Getting error New React version

### ISSUE THREAD

**Issue by ishaan-puniani** [sean-ww/react-redux-datatable#2]
Hello,
I am trying this component.
On application compiling I am getting error 
Module not found: Can't resolve 'react/lib/update' in 'C:\GitHub\node_modules\react-addons-update'

If you can please update it to work with latest verion of react as there are some breaking chnages in new update
https://github.com/facebook/react/issues/9207

My application 

  "dependencies": {
    "axios": "^0.18.0",
    "react-redux": "^5.0.7",
    "react": "^16.2.0",
    "react-redux-datatable": "^1.2.4",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.1",
    "redux": "^3.7.2",
    "redux-form": "^7.3.0",
    "url-search-params-polyfill": "^4.0.0",
    "connected-react-router": "^4.3.0"
  }

**Comment by sean-ww** [comment]
The current version doesn’t support react 16. I’m looking at migrating the project to use [react-bootstrap-table2](https://github.com/react-bootstrap-table/react-bootstrap-table2) along with updating to react 16. However, this will take time as react-bootstrap-table2 is still yet to fully implement all of the features from the first version. In the meantime I could recommend using react-bootstrap-table2 directly if it has the features you need.

**Comment by thclark** [comment]
@sean-ww nice work, this'll be a really useful component. But, any chance of putting a line about this into the install/quickstart guide? It'll save people going through a couple of hours installing / configuring the package only to find they can't use it! Cheers :)

**Comment by sean-ww** [comment]
@thclark thanks, it is listed in the peer dependencies which should then tell you straight away when you try to install it with the wrong version of react, unless I’m mistaken.

**Comment by thclark** [comment]
Thanks sean, unfortunately, it turns out that npm doesn't do that, because the ^15.x.y notation only indicates "compatible with this" rather than "not compatible with others". If it helps, dependencies can be given with  < x.y.z notation which would cause an error on install in that case :)

**Comment by sean-ww** [comment]
Ah that's good to know

**Comment by thclark** [comment]
Yeah, I'd really thought it meant something else until finding this! Lessons learned I guess :)
