### ISSUE TITLE
Unkonwn error

### ISSUE THREAD

**Issue by mehrdad-parsa68** [sean-ww/react-redux-datatable#58]
Hi
When I want to use this package in my project this error appeared.
My product built with react-redux and I use redux-observable.

Could not find "store" in either the context or props of "Connect(DataTableContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(DataTableContainer)".

Could you please help me?

Best regards

**Comment by sean-ww** [comment]
https://sean-ww.github.io/react-redux-datatable/get-started/get-started.html#include-reducer
Is that what you're missing?

**Comment by mehrdad-parsa68** [comment]
@sean-ww Actually i did it. I combined DataTableReducer to my reducers but the error still appeared

**Comment by sean-ww** [comment]
I haven't set it up before with redux-observable, so I'm not sure if that's the issue or not.
You can find a basic example of a store: https://github.com/sean-ww/react-redux-datatable/blob/master/src/example/src/store.jsx

That is then used in the storybook examples:
https://github.com/sean-ww/react-redux-datatable/blob/master/src/example/src/components/Story.jsx

react-redux-datatable is quite a high-level solution, and if you need something lower level that you can do more with then the underlying solution is [react-bootstrap-table2](https://react-bootstrap-table.github.io/react-bootstrap-table2/)

**Comment by dophlin** [comment]
@sean-ww, is it even important what kind of middlewares @mehrdad-parsa68 uses?
I mean, it seems the react-redux-datatable is not deeply related to Saga, RX, observables or anything else, it only uses redux and redux store for its functionality, and I guess it should work.

**Comment by sean-ww** [comment]
@dophlin yeah I can't see any obvious reason why there would be a link, it really should be unrelated. As long as you are still creating a store that it can connect to then it should work.

**Comment by mehrdad-parsa68** [comment]
I tried and solve the problem but new error appeared when i give it my API location :
Error: Actions must be plain objects. Use custom middleware for async actions.

**Comment by sean-ww** [comment]
Do you have the thunk middleware as shown in the example store?

**Comment by raycaballero** [comment]
I am having the same problem right now.

**Comment by vova111** [comment]
I am having the same problem right now.

**Comment by nishad-mangadan** [comment]
I am having the same problem, is there any solution for this? I am not using any middleware.

**Comment by nishad-mangadan** [comment]
> @dophlin yeah I can't see any obvious reason why there would be a link, it really should be unrelated. As long as you are still creating a store that it can connect to then it should work.

Is middleware like thunk or saga compulsory here?

**Comment by sean-ww** [comment]
It makes use of all middleware shown in the example (including redux-thunk):
https://github.com/sean-ww/react-redux-datatable/blob/master/src/example/src/store.jsx

They are dependencies of the project

**Comment by firmandev** [comment]
i have this error but when i put that in const Datatable it will different error 
 const DataTable = () => (
			<DataTable
			  tableSettings={tableSettings}
			  apiLocation={url}
			/>
		 );

it is loop forever i think the cause when the API is not correct.

**Comment by firmandev** [comment]
is this how to combine the reducer ? 

const allReducers = combineReducers({
    sidebar    : sideBarReducer,
    table      : sideBarTable,
    router     : router,
    DataTableReducer : DataTableReducer
});

**Comment by sean-ww** [comment]
Combining reducers example:
```jsx
import { combineReducers } from 'redux';
import { reducer as myOtherReducer } from 'react-redux-other';
import exampleReducer from 'core/app.reducer';
import somethingElseReducer from './Thing/Something.reducer';
import { DataTableReducer } from 'react-redux-datatable';

export default combineReducers({
    appReducer,
    other: myOtherReducer,
    exampleReducer,
    somethingElseReducer,
    DataTableReducer,
});
```
Combining reducers is not specific to react-redux-datatable, other than you must include the DataTablesReducer as shown.
It's exported, from the package:
https://github.com/sean-ww/react-redux-datatable/blob/master/src/index.jsx
There is nothing different from the example in the docs.

This package however is no longer actively maintained. If what's there work for you then it's good, but please be aware that it is not actively worked on.
