### ISSUE TITLE
Table showing all rows all rows, regardless of sizePerPage-dropdown is set to.

### ISSUE THREAD

**Issue by CodeBroJohn** [sean-ww/react-redux-datatable#62]
First of all, thanks for this great package, it has lots of awesome features. 

I am having an issue where my table will show the maximum number of rows returned regardless of if I set it to only show 10, 25, 50, or 100. 

Interestingly enough the pagination seems to work fine regardless. 

I am receiving an error that Each child in a list should have a unique "key" prop. 

I think this may be the cause of the error.

**Comment by CodeBroJohn** [comment]
I fixed the issue with the unique key prop. It seems to not have been related as the main issue persists.

**Comment by sean-ww** [comment]
Hi,
It's the responsibility of the api to return the correct number of rows. So changing the number of results per page or the page number will just change the values sent to your api. It results in the 'limit' (number of results), and 'offset' (the search offset, i.e. pagination, accounting for number per page) attributes changing.
See the overview of how that works:
https://sean-ww.github.io/react-redux-datatable/requesting-data/overview.html

If you want a table where you load in all data and then javascript sorts and searches it, then this is not it 👍
